### ISSUE TITLE
Enforce the display of the lowest available price on deal page, not only lowest price

### ISSUE THREAD

**Issue by julienmarie** [omatthiaso/MD-Desktop#1]
Sometimes, if the cheapest option is sold out, the displayed price is not updated and this set the wrong expectations for the customers.
We can update it quickly. This change needs to be done on all the platforms.
![70__Off_All-Day_Pass_to_Splash_Island_Promo_in_Laguna_-_SHT_-_Mozilla_Firefox](https://user-images.githubusercontent.com/189369/75746958-b4327e00-5d56-11ea-9e5a-f0b36328a53d.jpg)
![70__Off_All-Day_Pass_to_Splash_Island_Promo_in_Laguna_-_SHT_-_Mozilla_Firefox](https://user-images.githubusercontent.com/189369/75746968-b7c60500-5d56-11ea-9813-ff2c34f56d80.jpg)

**Comment by lenojnartel** [comment]
we will display the said option as sold out or no select button..

**Comment by lenojnartel** [comment]
this was fixed, being override the rate base on the minimum price in the options.
